(setq org-src-window-setup 'current-window)
(setq org-directory "~/src/doc")
(setq org-log-done 'time)
(setq org-todo-interpretation 'sequence)
(setq org-todo-keywords '("TODO" "BLOCK(b@/!)" "REVIEW(r@/!)" "WIP(w!)" "|" "DONE(d!)" "CANCELLED(c@)"))
(setq org-todo-keyword-faces '(("BLOCK" . link) ("REVIEW" . warning) ("WIP" . success)))
