;;; ric-keys-mode.el --- minor mode to set keybindings

;; Version: 0

(defun ric-key-translations ()
  "Make C-i and C-m available at hyper bindings."
  (when (display-graphic-p)
    (keyboard-translate ?\C-i ?\H-i)
    (keyboard-translate ?\C-m ?\H-m)))

;;;###autoload
(define-minor-mode ric-keys-mode
  "Set up global bindings to override other modes."
  :lighter " rk"
  :group 'keyboard
  :global t
  :init-value 1
  :after-hook (ric-key-translations)
  :keymap
  (let ((map (make-sparse-keymap)))
    (keymap-set map "C-<tab>" #'set-selective-display)
    (define-key map (kbd "<f12> +") 'global-text-scale-adjust)
    (define-key map (kbd "<f12> =") 'global-text-scale-adjust)
    (define-key map (kbd "<f12> -") 'global-text-scale-adjust)
    (define-key map (kbd "<f12> 0") 'global-text-scale-adjust)
    (define-key map (kbd "<f2>") #'font-height-decrease)
    (define-key map (kbd "<f3>") #'font-height-increase)
    (define-key map (kbd "<f4>") #'font-height-reset)
    (define-key map (kbd "C-'") #'ric-mark-string-forward)
    (define-key map (kbd "C-(") #'ric-mark-paren-backward)
    (define-key map (kbd "C-)") #'ric-mark-paren-forward)
    (define-key map (kbd "C-,") #'previous-buffer)
    (define-key map (kbd "C-.") #'next-buffer)
    (define-key map (kbd "C-;") #'comment-or-uncomment-region)
    (define-key map (kbd "C-\\") #'mark-sexp)
    (define-key map (kbd "C-`") #'ric-mark-string-backward)
    ;; (define-key map (kbd "C-1") #'delete-other-windows)
    ;; (define-key map (kbd "C-2") #'digit-argument)
    ;; (define-key map (kbd "C-3") #'digit-argument)
    ;; (define-key map (kbd "C-3") #'split-window-right)
    (define-key map (kbd "C-c '") #'ruby-toggle-string-quotes)
    ;; (define-key map (kbd "C-c a") #'append-to-buffer)
    (define-key map (kbd "C-c L") #'link-hint-copy-link)
    (define-key map (kbd "C-c R") #'ric-code-review-link-hint)
    (define-key map (kbd "C-c b") #'project-switch-to-buffer)
    (define-key map (kbd "C-c c") #'org-capture)
    (define-key map (kbd "C-c d") #'duplicate-dwim)
    ;; (define-key map (kbd "C-c e") #'eshell)
    (define-key map (kbd "C-c f") #'recentf)
    (define-key map (kbd "C-c g") #'magit-file-dispatch)
    (define-key map (kbd "C-c h") #'eldoc)
    (define-key map (kbd "C-c i") #'string-inflection-all-cycle)
    (define-key map (kbd "C-c j") #'avy-goto-word-1)
    (define-key map (kbd "C-c k") #'kill-whole-line)
    (define-key map (kbd "C-c l") #'link-hint-open-link)
    (define-key map (kbd "C-c m") #'mu4e)
    (define-key map (kbd "C-c o") #'org-agenda)
    (define-key map (kbd "C-c p") #'project-switch-project)
    (define-key map (kbd "C-c r") #'rg)
    (define-key map (kbd "C-c s") #'magit-branch-checkout)
    (define-key map (kbd "C-c t") #'vterm)
    (define-key map (kbd "C-c u") #'winner-undo)
    (define-key map (kbd "C-c v") #'view-mode)
    (define-key map (kbd "C-c y") #'browse-kill-ring)
    (define-key map (kbd "C-j") #'avy-goto-char)
    (define-key map (kbd "C-h C-,") #'bs-show)
    ;; (define-key map (kbd "C-t") #'switch-to-buffer)
    (define-key map (kbd "C-x C-z") nil)
    (define-key map (kbd "C-x d") #'dired-jump)
    (define-key map (kbd "C-x g") #'magit-status)
    (define-key map (kbd "C-x k") #'kill-current-buffer)
    (keymap-set map "C-x m" #'smex)
    (define-key map (kbd "C-z") #'zap-up-to-char)
    (define-key map (kbd "H-i") #'project-find-file)
    (define-key map (kbd "H-m") #'easy-kill)
    (define-key map (kbd "M-Q") #'ric-unfill-paragraph)
    (define-key map (kbd "M-g l") #'avy-goto-line)
    (define-key map (kbd "M-i") #'imenu)
    (define-key map (kbd "M-o") #'project-find-file)
    (define-key map (kbd "ESC <down>") #'end-of-buffer)
    (define-key map (kbd "ESC <up>") #'beginning-of-buffer)
    (define-key map (kbd "S-<down>") #'other-window)
    (define-key map (kbd "S-<up>") #'(lambda () (interactive) (other-window -1)))
    (define-key map (kbd "s-<up>") #'enlarge-window)
    (define-key map (kbd "s-<down>") #'shrink-window)
    (define-key map (kbd "s-<right>") #'enlarge-window-horizontally)
    (define-key map (kbd "s-<left>") #'shrink-window-horizontally)
    map))

(provide 'ric-keys-mode)
